version: '3'
services:
  gerrit:
    image: gerritcodereview/gerrit:latest
    ports:
      - "8080:8080"
      - "29418:29418"
    volumes:
      - gerrit_data:/var/gerrit
    environment:
      - CANONICAL_WEB_URL=http://10.11.53.35:8080
    entrypoint: |
      sh -c '
        echo "Starting Gerrit initialization..."
        
        # Check if already initialized
        if [ ! -d /var/gerrit/git/All-Projects ]; then
          echo "Initializing Gerrit database..."
          /var/gerrit/bin/gerrit.sh init -d /var/gerrit --batch --install-all-plugins --no-auto-start
        else
          echo "Gerrit already initialized"
        fi
        
        # Set basic config
        git config -f /var/gerrit/etc/gerrit.config gerrit.canonicalWebUrl "http://10.11.53.35:8080"
        git config -f /var/gerrit/etc/gerrit.config auth.type "DEVELOPMENT_BECOME_ANY_ACCOUNT"
        
        echo "========================================"
        echo "Gerrit starting with development auth"
        echo "Access: http://10.11.53.35:8080"
        echo "Login: Click Sign In -> Become -> Enter username"
        echo "========================================"
        
        # Start in foreground
        /var/gerrit/bin/gerrit.sh run
      '

volumes:
  gerrit_data:
